
In Python, import torch refers to the main PyTorch library. However, "PyTorch" is the name of the overall framework, while "torch" is the actual package name used when importing in code

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.dtype

torch.int64

In [6]:
scalar.item()

7

In [7]:
vec=torch.tensor([7,7])
vec


tensor([7, 7])

In [8]:
vec.shape

torch.Size([2])

In [10]:
matrix=torch.tensor([[4,6],
                     [8,7]])
matrix

tensor([[4, 6],
        [8, 7]])

In [11]:
matrix[0]

tensor([4, 6])

**Random tensors**

In [13]:
rand_tens=torch.rand(3,4)
rand_tens

tensor([[0.8306, 0.2442, 0.0931, 0.5541],
        [0.7526, 0.3301, 0.4390, 0.8991],
        [0.9216, 0.9267, 0.6493, 0.2260]])

In [15]:
rand_img=torch.rand(size=(224,224,3))
print(rand_img.shape)
print(rand_img.ndim)

torch.Size([224, 224, 3])
3


In [17]:
zero=torch.zeros(size=(3,4))
print(zero)
ones=torch.ones(size=(3,4))
print(ones)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [18]:
ones.dtype

torch.float32

In [21]:
import tensorflow as tf
on=tf.ones([3,4])

In [22]:
on

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [24]:
on.dtype==ones.dtype

False

In [ ]:
# Create a PyTorch tensor
torch_tensor = torch.tensor([[1, 2], [3, 4]])

# Convert to NumPy
numpy_array = torch_tensor.numpy()

# Convert to TensorFlow tensor
tf_tensor = tf.convert_to_tensor(numpy_array)

In [ ]:

# Create a TensorFlow tensor
tf_tensor = tf.constant([[1, 2], [3, 4]])

# Convert to NumPy
numpy_array = tf_tensor.numpy()

# Convert to PyTorch tensor
torch_tensor = torch.from_numpy(numpy_array)


**Using NumPy as an intermediary is a common approach, but it's not strictly necessary.**

**Range**

In [26]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
dat=torch.arange(start=0,end=1000,step=77)

In [29]:
dat

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [30]:
ten_zeros=torch.zeros_like(input=dat)
print(ten_zeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


**tensor datatypes**

In [31]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],dtype=None)

In [33]:
float_32_tensor.dtype

torch.float32

In [34]:
 float_16_tensor=torch.tensor([3.0,6.0,9.0],dtype=torch.float16)
 float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [36]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],dtype=None,
                             device=None,
                             requires_grad=False)


In [37]:
float_32_tensor

tensor([3., 6., 9.])

requires_grad=False<br>
pytorch to track gradients of tensor when under goes some numerical calculations

In [38]:
 fl_16=float_32_tensor.type(torch.float16)
 fl_16

tensor([3., 6., 9.], dtype=torch.float16)

**math operations**

In [43]:
fl_16

tensor([3., 6., 9.], dtype=torch.float16)

In [40]:
fl_16*10

tensor([30., 60., 90.], dtype=torch.float16)

In [41]:
fl_16-10

tensor([-7., -4., -1.], dtype=torch.float16)

In [42]:
fl_16+7

tensor([10., 13., 16.], dtype=torch.float16)

In [ ]:
#elementwise multiplication
# tensor * tensor

#matrix multiplication
#torch.matmul(tensor,tensor)


**shape error is common**
- inner dimensions must match

## aggregations

In [66]:
x=torch.arange(0,100,10)

In [46]:
print(x)
print(torch.min(x))
print(x.min())

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
tensor(0)
tensor(0)


In [47]:
torch.max(x)

tensor(90)

In [49]:
torch.mean(x)
#int64 is Long - torch wont work

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [50]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [51]:
x.type(torch.float32).mean()

tensor(45.)

In [53]:
torch.sum(x)
#x.sum()

tensor(450)

### Positional min and max
 - argmax,argmin

In [54]:
x.argmin()

tensor(0)

In [55]:
x.argmax()

tensor(9)

In [56]:
x[9]

tensor(90)

- Reshape
- stacking
- squeezing
- unsqueezing

In [61]:
print(x)
print(x.shape)
print(x.reshape(1,10))
print(x.reshape(10,1))
print(x)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
torch.Size([10])
tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])
tensor([[ 0],
        [10],
        [20],
        [30],
        [40],
        [50],
        [60],
        [70],
        [80],
        [90]])
tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


In [67]:
#change view
print(x)
z=x.view(1,10)
#view has memory with original tensor
#changing z changes x
z[:,0]=5
z,x


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


(tensor([[ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90]]),
 tensor([ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90]))

In [68]:
#stack

x_stacked=torch.stack([x,x,x])
print(x_stacked)

tensor([[ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90]])


In [69]:
x_stacked=torch.stack([x,x,x],dim=1)
print(x_stacked)

tensor([[ 5,  5,  5],
        [10, 10, 10],
        [20, 20, 20],
        [30, 30, 30],
        [40, 40, 40],
        [50, 50, 50],
        [60, 60, 60],
        [70, 70, 70],
        [80, 80, 80],
        [90, 90, 90]])


In [82]:
x_reshaped=x.reshape(1,1,10)
x_reshaped

tensor([[[ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90]]])

In [83]:
#squeeze
#removes all single dimentions from a target tensor
print(x_reshaped)
x_sqx=x_reshaped.squeeze()
print(x_sqx)

tensor([[[ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90]]])
tensor([ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90])


In [84]:
#unsqueeze adds a single dimention to a target tensor at a specific dim
x_unsq=x_sqx.unsqueeze(dim=0)
print(x_unsq)

tensor([[ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90]])


In [86]:
#permute
x=torch.randn(2,3,5)
x.size()

torch.Size([2, 3, 5])

In [88]:
torch.permute(x,(2,0,1)).size() #change the order of dimentions 2 is now 0,0 is now 1 and 1 is now 2

torch.Size([5, 2, 3])

**Indexing**
- is similar to numpy indexing

In [89]:
x=torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [90]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [91]:
x[0][0]

tensor([1, 2, 3])

In [93]:
x[:,:,0]

tensor([[1, 4, 7]])

**Reproducbility**

In [99]:
random_seed=43
torch.manual_seed(random_seed)
rand_a=torch.rand(3,4)

torch.manual_seed(random_seed)
rand_b=torch.rand(3,4)
print(rand_a)
print(rand_b)

tensor([[0.4540, 0.1965, 0.9210, 0.3462],
        [0.1481, 0.0858, 0.5909, 0.0659],
        [0.7476, 0.6253, 0.9392, 0.1338]])
tensor([[0.4540, 0.1965, 0.9210, 0.3462],
        [0.1481, 0.0858, 0.5909, 0.0659],
        [0.7476, 0.6253, 0.9392, 0.1338]])


**gpu**

- change runtime type to gpu in colab (if working in colab)

In [1]:
!nvidia-smi

Wed Oct  9 05:31:02 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [4]:
#check for gpu
import torch
torch.cuda.is_available()

True

In [7]:
 #setup device agnostic code
 device="cuda" if torch.cuda.is_available() else "cpu"

In [10]:
print(device)
pytorch
torch.cuda.device_count()

cuda


1

## putting tensors on gpu

In [11]:

ten=torch.tensor([1,2,3],device="cpu")
print(ten,ten.device)


tensor([1, 2, 3]) cpu


In [12]:
ten_gp=ten.to(device)
ten_gp.device

device(type='cuda', index=0)

In [13]:
# moving back to cpu
ten_gp.numpy()
#cant convert to numpy if on gpu

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [14]:
ten_cp=ten_gp.cpu().numpy()
ten_cp

array([1, 2, 3])